#!/bin/bash
. ../demo-magic.sh
clear

N=secrets

pe "kubectl create namespace $N"
pe "kubectl create secret generic mysql --from-literal=password=NoTv3ry5Ecre7 --from-literal=user=root -n $N"
pe "cat secretgetter.yaml"
pe "kubectl create -f secretgetter.yaml -n $N"
pe "kubectl exec -n $N -it secrets -- env"
pe "cat secretmount.yaml"
#pe "kubectl apply -f secretmount.yaml -n $N"
#pe "kubectl exec -n $N -it secrets -- ls /mysql"
pe "kubectl delete namespace $N"