#!/bin/bash
export AWS_REGION=eu-west-2
export CLUSTER=dev-cluster
#create cluster
eksctl create cluster -f cluster.yaml --kubeconfig ~/.kube/config-dev-cluster

export CLUSTER_EP=$(aws eks describe-cluster \
    --region $AWS_REGION \
    --name $CLUSTER \
    --query "cluster.endpoint" \
    --output text)

export CA=$(aws eks describe-cluster \
    --region $AWS_REGION \
    --name $CLUSTER \
    --query "cluster.certificateAuthority.data" \
    --output text)

cat << EOF > ~/.kube/config-dev-cluster
apiVersion: v1
clusters:
- cluster:
    server: $CLUSTER_EP
    certificate-authority-data: $CA
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
        - "eks"
        - "get-token"
        - "--cluster-name"
        - "$CLUSTER"
        # - "--role-arn"
        # - "role-arn"
      # env:
        # - name: AWS_PROFILE
        #   value: "aws-profile"
EOF

export KUBECONFIG=~/.kube/config-dev-cluster
