#!/bin/bash
. ../demo-magic.sh
clear
NS=demo
pe "kubectl create ns $NS"
pe "kubectl apply -f ../simple-image/app_pod.yaml -n $NS"
#pe "kubectl run web --image=httpd"
pe "kubectl taint node worker status=dodgy:NoSchedule  -n $NS"
pe "kubectl run web --image=nginx  -n $NS"
pe "kubectl delete po web  -n $NS"
pe "kubectl taint node worker status=dodgy:NoSchedule-"
pe "kubectl taint node worker status=flaky:NoExecute"
pe "kubectl apply -f ../simple-image/app_pod.yaml  -n $NS"
#pe "kubectl run web --image=httpd"
pe "kubectl delete po myapp  -n $NS"
pe "tail ./tolerant_pod.yaml"
pe "kubectl apply -f ./tolerant_pod.yaml -n $NS"
pe "kubectl apply -f ./tolerant_pod.yaml -n $NS"
pe "kubectl taint node worker status=flaky:NoExecute-"
pe "kubectl delete po myapp  -n $NS"
