#!/bin/bash
curl -sL https://run.linkerd.io/install | sh

echo "export PATH=$PATH:~/.linkerd2/bin" >> ~/.bashrc

linkerd check --pre

linkerd install | kubectl apply -f -

linkerd check

linkerd viz install | kubectl apply -f -

linkerd viz check

INDEX=$(kubectl get deploy web -n linkerd-viz -o json  | jq '.spec.template.spec.containers[0].args | map(.name == "-enforce-host") | index(true)')

kubectl patch deploy web --type=json -p="[{'op': 'remove', 'path': '.spec.template.spec.containers[0].args[$INDEX]'}]" -n linkerd-viz

kubectl patch deploy web \
    --type=json \
    -p='[{"op":"add", "path":"/spec/template/spec/containers/0/args/-", "value":"--enforce-host="}]' -n linkerd-viz