#!/bin/bash
curl -sL https://run.linkerd.io/install | sh

echo "export PATH=$PATH:~/.linkerd2/bin" >> ~/.bashrc

linkerd check --pre

linkerd install | kubectl apply -f -

linkerd check

linkerd viz install | kubectl apply -f -

linkerd check