#!/bin/bash
curl -sL https://run.linkerd.io/install | sh

export PATH=$PATH:/home/ubuntu/.linkerd2/bin

linkerd check --pre

linkerd install | kubectl apply -f -

linkerd check

linkerd viz install | kubectl apply -f -

linkerd check