#!/bin/bash

helm repo add linkerd https://helm.linkerd.io/stable

helm repo update

exp=$(date -d '+8760 hour' +"%Y-%m-%dT%H:%M:%SZ")

helm install linkerd-crds linkerd/linkerd-crds \
  -n linkerd --create-namespace
  
helm install linkerd-control-plane \
  -n linkerd \
  --set-file identityTrustAnchorsPEM=ca.crt \
  --set-file identity.issuer.tls.crtPEM=issuer.crt \
  --set-file identity.issuer.tls.keyPEM=issuer-private.pem \
  --set identity.issuer.crtExpiry=$exp \
  linkerd/linkerd-control-plane

helm install linkerd-viz -n linkerd-viz \
  --create-namespace linkerd/linkerd-viz \
  --set enforcedHostRegexp=.*

# set dashboard to NodePort