#!/bin/bash

helm repo add linkerd https://helm.linkerd.io/stable

helm repo update

exp=$(date -d '+8760 hour' +"%Y-%m-%dT%H:%M:%SZ")

helm install linkerd-crds linkerd/linkerd-crds \
  -n linkerd --create-namespace
  
helm install linkerd-control-plane \
  -n linkerd \
  --set-file identityTrustAnchorsPEM=ca.crt \
  --set-file identity.issuer.tls.crtPEM=issuer.crt \
  --set-file identity.issuer.tls.keyPEM=issuer-private.pem \
  --set identity.issuer.crtExpiry=$exp \
  --set identity.issuer.scheme=kubernetes.io/tls \
  linkerd/linkerd-control-plane

helm install linkerd-viz -n linkerd-viz \
  --create-namespace linkerd/linkerd-viz \
  --set dashboard.enforcedHostRegexp=.*

# set dashboard to NodePort
kubectl patch service \
  web --namespace linkerd-viz \
  --type='json' \
  -p='[{"op": "replace", "path": "/spec/type", "value": "NodePort" }]'
# set NodePort to 32500
kubectl patch service \
  web --namespace linkerd-viz \
  --type='json' \
  -p='[{"op": "replace", "path": "/spec/ports/0/nodePort", "value": 31500 }]'

#install linkerd cli
curl -sL https://run.linkerd.io/install | sh
echo 'export PATH=$PATH:~/.linkerd2/bin' >> ~/.bashrc
source ~/.bashrc

#install smi
helm repo add l5d-smi https://linkerd.github.io/linkerd-smi
helm install l5d-smi/linkerd-smi --generate-name

#still a problem with TAP though. Certs I think.