#!/bin/bash
export AWS_REGION=eu-west-2
curl https://raw.githubusercontent.com/aws-samples/amazon-cloudwatch-container-insights/latest/k8s-deployment-manifest-templates/deployment-mode/daemonset/container-insights-monitoring/quickstart/cwagent-fluentd-quickstart.yaml | sed "s/{{cluster_name}}/dev-cluster/;s/{{region_name}}/$AWS_REGION/" | kubectl apply -f -