#!/bin/bash
helm repo add gatekeeper https://open-policy-agent.github.io/gatekeeper/charts
helm install gatekeeper/gatekeeper --name-template=gatekeeper --namespace gatekeeper-system --create-namespace
cd ~
git clone https://github.com/open-policy-agent/gatekeeper.git