#!/bin/bash
helm repo add dashboard https://kubernetes.github.io/dashboard

helm install kubernetes-dashboard dashboard/kubernetes-dashboard \
    --set protocolHttp=true \
    --set service.type=NodePort \
    --set metricsScraper.enabled=true \
    --version 6.0.8

kubectl create clusterrolebinding dashaccess \
    --clusterrole cluster-admin \
    --serviceaccount default:kubernetes-dashboard