#!/bin/bash
helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install prometheus bitnami/kube-prometheus \
    --set prometheus.service.type=NodePort \
    --set alertmanager.service.type=NodePort \
    --namespace monitoring \
    --create-namespace