FROM python:3.9-slim-bullseye

RUN adduser --system --group --no-create-home appuser
RUN mkdir /data && chown appuser /data

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./app2 /code/app

USER appuser

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]