#!/bin/bash
aws ec2 describe-instance-types \
    --filters "Name=instance-type,Values=$1" \
    --query "InstanceTypes[].{Type: InstanceType, MaxENI: NetworkInfo.MaximumNetworkInterfaces, IPv4addr: NetworkInfo.Ipv4AddressesPerInterface}" \
    --output table