#!/bin/bash
. ../../demo-magic.sh
clear
REGION=eu-west-2
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

pe "docker build -t hello-world ."

pe "docker images --filter reference=hello-world"

pe 'aws ecr create-repository \
    --repository-name hello-world \
    --image-scanning-configuration scanOnPush=true \
    --region '"$REGION"


pe "aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com"

pe "docker tag hello-world:latest $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/hello-world:latest"

pe "docker push $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/hello-world:latest"

# tidy up
pe "aws ecr delete-repository --repository-name hello-world --force"