# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: products.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\"F\n\x12ProductListRequest\x12\x1b\n\x08\x63\x61tegory\x18\x01 \x01(\x0e\x32\t.Category\x12\x13\n\x0bmax_results\x18\x02 \x01(\x05\"2\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\"1\n\x13ProductListResponse\x12\x1a\n\x08products\x18\x01 \x03(\x0b\x32\x08.Product*%\n\x08\x43\x61tegory\x12\x08\n\x04\x42OOK\x10\x00\x12\x06\n\x02\x43\x44\x10\x01\x12\x07\n\x03\x44VD\x10\x02\x32\x45\n\x08Products\x12\x39\n\x0cListProducts\x12\x13.ProductListRequest\x1a\x14.ProductListResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CATEGORY._serialized_start=193
  _CATEGORY._serialized_end=230
  _PRODUCTLISTREQUEST._serialized_start=18
  _PRODUCTLISTREQUEST._serialized_end=88
  _PRODUCT._serialized_start=90
  _PRODUCT._serialized_end=140
  _PRODUCTLISTRESPONSE._serialized_start=142
  _PRODUCTLISTRESPONSE._serialized_end=191
  _PRODUCTS._serialized_start=232
  _PRODUCTS._serialized_end=301
# @@protoc_insertion_point(module_scope)
