#!/bin/bash

#install helm
# curl -sSL https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

#or:
wget https://get.helm.sh/helm-v3.8.0-linux-amd64.tar.gz
tar -zxvf helm*linux-amd64.tar.gz
sudo mv linux-amd64/helm /usr/local/bin/helm