#!/bin/bash
. ../demo-magic.sh
clear

N=secrets

pe "kubectl create namespace $N"
pe "kubectl create secret generic mysql --from-literal=password=NoTv3ry5Ecre7 --from-literal=user=root -n $N"
pe "kubectl get secret mysql -n $N"
pe "kubectl describe secret mysql -n $N"